### ISSUE TITLE
LAYOUT - Nav

### ISSUE THREAD

**Issue by ricardolopezg** [ricardolopezg/nycda_project_micro_blogging_app#2]
Nav positioned to the right 

Nav tab order: 
HOME (general feed)  >  BROWSE  >  PROFILE  >  USERNAME (hover/click for submenu: ACCOUNT & LOGOUT

**Comment by ricardolopezg** [comment]
Nav positioned to the right

**Comment by DanielWolkowitz** [comment]
done
